"""Cross-reference the Appendix C tables from the chapters that rest on them.

Appendix C was built from the evaluation CSVs that fed no table in the document.
Nine of its ten tables were then reachable only through the List of Tables, which
makes an appendix read as padding rather than as evidence: a supporting table that
nothing points at is not supporting anything.

Chapters 4 and 5 are regenerated by build_chapter4.py and build_chapter5.py on
every run of finalise_dissertation.sh, so the pointers to Tables C.5 to C.8 live
in those generators. Chapters 2 and 3 are edited in place, so theirs are here:

    C.2, C.3  the two pixel-wise grids, from Section 3.6.7
    C.4       the neural grid, from Section 3.6.7
    C.9       the perfect-prognosis transfer test, from Section 3.4.4
    C.10      the physiographic band means, from Section 2.4.3

Idempotent: each edit is keyed on text that the replacement does not reproduce,
and a second run reports the edits as already applied rather than doubling them.

    python add_appendix_c_crossrefs.py
"""

import os
import shutil
import sys

import docx

ROOT = os.path.dirname(os.path.abspath(__file__))
CH = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-Personal(2)/UNI ZIM/PROJECT CHAPTERS")
DOC = os.path.join(CH, "CR_Madukwe_Dissertation.docx")
LOCK = os.path.join(CH, "~$_Madukwe_Dissertation.docx")

EDITS = [
    # Section 3.6.7, the neural grid.
    ("For the two neural architectures the search covered the learning rate "
     "and, for the CNN, the loss weighting.",
     "For the two neural architectures the search covered the learning rate "
     "and, for the CNN, the loss weighting; Appendix C, Table C.4, gives both "
     "grids with every candidate's inner-split score."),

    # Section 3.6.7, the two pixel-wise grids.
    ("The XGBoost values for eta, subsample and minimum child weight all lie "
     "outside the grid of Table 3.2, so the search could never have returned "
     "that configuration; the Random Forest values do lie inside it.",
     "The XGBoost values for eta, subsample and minimum child weight all lie "
     "outside the grid of Table 3.2, so the search could never have returned "
     "that configuration; the Random Forest values do lie inside it. Both grids "
     "are reported in full in Appendix C, Tables C.2 and C.3."),

    # Section 3.4.4, the perfect-prognosis transfer test.
    ("The transfer of that relationship from ERA5 to CMIP6 predictors becomes a "
     "testable step in its own right, and is tested.",
     "The transfer of that relationship from ERA5 to CMIP6 predictors becomes a "
     "testable step in its own right, and is tested: Appendix C, Table C.9, "
     "applies each deployed model to every driving model's bias-corrected "
     "predictors over the historical period and scores the result against the "
     "field the model was trained to reproduce."),

    # Section 2.4.3, the physiographic band means.
    ("Because the band means span only 3.2 per cent while distance to the "
     "transmission network varies over two orders of magnitude, it is grid "
     "access and not resource quality that decides between sites, as Sections "
     "4.8.1 and 5.2.4 report.",
     "Because the band means span only 3.2 per cent while distance to the "
     "transmission network varies over two orders of magnitude, it is grid "
     "access and not resource quality that decides between sites, as Sections "
     "4.8.1 and 5.2.4 report. Appendix C, Table C.10, gives the band means in "
     "both observed products."),
]


def is_field(r):
    x = r._r.xml
    return ("fldChar" in x) or ("instrText" in x)


def apply(par, old, new):
    for r in par.runs:
        if old in r.text:
            r.text = r.text.replace(old, new, 1)
            return True
    runs = par.runs
    full = "".join(r.text for r in runs)
    at = full.find(old)
    if at < 0:
        return False
    starts, pos = [], 0
    for r in runs:
        starts.append(pos)
        pos += len(r.text)
    f = max(i for i, st in enumerate(starts) if st <= at)
    l = max(i for i, st in enumerate(starts) if st < at + len(old))
    span = runs[f:l + 1]
    if any(is_field(r) for r in span):
        return False
    acc = "".join(r.text for r in span)
    k = acc.find(old)
    span[0].text = acc[:k] + new + acc[k + len(old):]
    for r in span[1:]:
        r.text = ""
    return True


def main():
    if os.path.exists(LOCK):
        print("The dissertation is open in Word. Close it first.")
        return 2
    d = docx.Document(DOC)
    NS = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}sectPr"
    before = (d.element.xml.count("ZOTERO_ITEM"),
              d.element.xml.count('w:fldCharType="begin"'),
              len(d.element.body.findall(NS)))
    done = left = 0
    for old, new in EDITS:
        # Already applied when the pointer is present; the key text survives the
        # edit, so presence of the key alone does not mean outstanding.
        tail = new[len(old):].strip() if new.startswith(old) else new[-60:]
        if any(tail[:50] in p.text for p in d.paragraphs):
            print("  already applied: %s" % old[:50])
            continue
        par = next((p for p in d.paragraphs if old in p.text), None)
        if par is None:
            left += 1
            print("  NOT FOUND: %s" % old[:50])
            continue
        if apply(par, old, new):
            done += 1
            print("  referenced: %s" % tail[:62])
        else:
            left += 1
            print("  SPANS A FIELD, skipped: %s" % old[:50])

    if not done:
        print("nothing to change")
        return 0 if left == 0 else 1
    bak = DOC.replace(".docx", "_BACKUP_pre_appendixc_refs.docx")
    shutil.copy(DOC, bak)
    d.save(DOC)
    dd = docx.Document(DOC)
    ax = dd.element.xml
    after = (ax.count("ZOTERO_ITEM"), ax.count('w:fldCharType="begin"'),
             len(dd.element.body.findall(NS)))
    if after != before:
        shutil.copy(bak, DOC)
        print("STRUCTURE CHANGED %s -> %s, restored" % (before, after))
        return 1
    print("%d referenced, %d outstanding; citations/fields/sections intact %s"
          % (done, left, after))
    return 0


if __name__ == "__main__":
    sys.exit(main())
