"""Apply the author's edits from a hand-edited merged dissertation back to source.

Context. The merged dissertation is a build product: Chapters 4 and 5 are
generated from the analysis outputs and the front matter is generated by
build_thesis.py, so anything typed into the merged file is destroyed by the next
build. The author edited the merged file; this script pushes those edits back to
the files the build actually reads, which is the only place they survive.

Chapters 1 to 3 are hand-written and are edited in place here. Front-matter edits
are NOT applied by this script: they live in build_thesis.py and are made there by
hand, because they are prose the generator emits rather than prose it copies.

Method. Each differing paragraph is matched to its source paragraph, then only the
minimal changed spans are written, into the specific run that contains them. Whole
paragraphs are never rebuilt, because a Zotero citation occupies several runs of a
paragraph and flattening them destroys the field - which has already happened once
in this project and was caught only by counting fields before and after.

    python apply_author_edits.py --edited path/to/edited.docx [--dry-run]
"""

import argparse
import difflib
import os
import re
import shutil
import sys

import docx

CHAPTERS = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-Personal(2)/UNI ZIM/PROJECT CHAPTERS")
SOURCES = ["CR_Madukwe_Chapter 1_corrected.docx",
           "CR_Madukwe_Chapter2.docx",
           "CR_Madukwe_Chapter3_Final.docx"]

norm = lambda s: re.sub(r"\s+", " ", s or "").strip()


def integrity(path):
    d = docx.Document(path)
    x = d.element.xml
    return (x.count("ZOTERO_ITEM"), x.count('w:fldCharType="begin"'),
            x.count('w:fldCharType="end"'), len(d.tables))


def edit_spans(old, new):
    """The minimal (old_text, new_text) replacements turning old into new.

    Computed on WORD tokens, not characters. A character-level diff widened to
    word boundaries produces overlapping spans - the first version of this
    produced both ("MSc.", "Master of Science") and ("MSc.", "Science in") for
    one edit, and applying both would corrupt the sentence. Word tokens make the
    spans non-overlapping by construction.

    Each span carries one word of surrounding context where the changed text is
    short, so that the replacement can be located unambiguously inside a run.
    """
    ow, nw = old.split(" "), new.split(" ")
    sm = difflib.SequenceMatcher(None, ow, nw, autojunk=False)
    spans = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        # pad with context until the old side is long enough to be unique
        while (i2 - i1) < 3 and (i1 > 0 or i2 < len(ow)):
            if i1 > 0:
                i1 -= 1
                j1 -= 1
            elif i2 < len(ow):
                i2 += 1
                j2 += 1
            if old.count(" ".join(ow[i1:i2])) == 1:
                break
        o, n = " ".join(ow[i1:i2]), " ".join(nw[max(j1, 0):max(j2, 0)])
        if o != n:
            spans.append((o, n))
    return spans


def apply_to_paragraph(par, old_text, new_text):
    """Write the changed spans into the runs that hold them. Returns n applied."""
    applied = 0
    for old_s, new_s in edit_spans(old_text, new_text):
        if not old_s or old_s == new_s:
            continue
        for run in par.runs:
            if old_s in run.text:
                run.text = run.text.replace(old_s, new_s, 1)
                applied += 1
                break
    return applied


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--edited", required=True)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    edited = [norm(q.text) for q in docx.Document(args.edited).paragraphs]
    edited = [e for e in edited if e]

    total = 0
    for name in SOURCES:
        path = os.path.join(CHAPTERS, name)
        doc = docx.Document(path)
        before = integrity(path)
        changes = []

        # Everything from a chapter's References heading onward is a
        # Zotero-generated bibliography. The edited document carries a single
        # consolidated list instead, so the matcher would happily pair each
        # chapter entry with my normalised version of it and rewrite a generated
        # bibliography with ASCII-folded names. Nothing below that heading is an
        # author edit, so nothing below it is touched.
        in_refs = False
        for par in doc.paragraphs:
            t = norm(par.text)
            if par.style.name.startswith("Heading") and t.lower() in (
                    "references", "bibliography"):
                in_refs = True
            if in_refs:
                continue
            if len(t) < 40:
                continue
            if t in edited:
                continue                      # unchanged
            # closest surviving paragraph in the edited document
            near = difflib.get_close_matches(t, edited, n=1, cutoff=0.80)
            if not near:
                continue                      # deleted by the author, or new text
            if near[0] == t:
                continue
            changes.append((par, t, near[0]))

        print("\n%s: %d paragraph(s) changed" % (name, len(changes)))
        for par, old, new in changes:
            spans = edit_spans(old, new)
            has_field = "ZOTERO" in par._p.xml
            print("   %s%d span(s)%s" % ("[has citation field] " if has_field else "",
                                         len(spans), ""))
            for o, n in spans[:4]:
                print("       - %s" % o[:96])
                print("       + %s" % n[:96])
            if not args.dry_run:
                got = apply_to_paragraph(par, old, new)
                if got != len(spans):
                    print("       !! applied %d of %d spans; paragraph left partly "
                          "unchanged, apply the rest by hand" % (got, len(spans)))
            total += len(spans)

        if changes and not args.dry_run:
            shutil.copy(path, path.replace(".docx", "_BACKUP_pre_author_edits.docx"))
            doc.save(path)
            after = integrity(path)
            ok = before == after
            print("   saved | citation fields %s (%s -> %s)"
                  % ("intact" if ok else "CHANGED", before, after))
            if not ok:
                print("   !! restoring from backup, edit not applied")
                shutil.copy(path.replace(".docx", "_BACKUP_pre_author_edits.docx"), path)

    print("\n%d span(s) %s" % (total, "found (dry run)" if args.dry_run else "applied"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
