#!/usr/bin/env bash
# Rebuild the results chapters and put the dissertation back in order.
#
# The steps must run in this order. Splicing imports the generators' output
# verbatim, so the presentation pass, the table formatting and the front-matter
# lists all have to follow it; running the splice alone silently reintroduces the
# generator's units, spacing and an unformatted table.
set -e
cd "$(dirname "$0")"
PY=/opt/anaconda3/envs/climate_stack/bin/python
export KMP_DUPLICATE_LIB_OK=TRUE

echo "=== 1/8 regenerate the results chapters ==="
$PY build_chapter4.py >/dev/null
$PY build_chapter5.py >/dev/null

echo "=== 2/8 splice them into the dissertation ==="
$PY splice_results_chapters.py | grep -vE '^\s*$' | tail -4

# The abstract is read from the CSVs too, and must be regenerated here. Leaving
# it out is how it froze at a superseded run while every chapter moved on, and an
# examiner found five different figures for one quantity.
echo "=== 3/8 abstract, from the CSVs ==="
$PY rewrite_abstract.py | tail -2

echo "=== 4/8 presentation: spacing, alignment, units, metadata ==="
$PY fix_presentation.py | tail -3

echo "=== 5/8 factual corrections (idempotent) ==="
$PY fix_facts.py | tail -1
# Chapter 3 is not regenerated by this chain, so corrections to it live in
# scripts that run here. Both are idempotent and report "nothing to change"
# once applied; they are in the chain so a fresh checkout reproduces the
# document rather than only the chapters the generators own.
$PY fix_unet_refit_recorded.py | tail -1
$PY add_appendix_c_crossrefs.py | tail -1
$PY fix_methods_chapter_result_values.py | tail -1
$PY fix_method_citations_v7.py | tail -1
# Adds any work cited in the body but absent from the bibliography, as plain
# text that a Zotero refresh replaces. Idempotent.
$PY insert_missing_references.py | tail -1

# Lists BEFORE table formatting: the abbreviations list is itself a table, so
# formatting first leaves it in the generator's style.
# Appendix C is generated from the evaluation CSVs, so it has to be rebuilt here
# and must precede the lists, which index its captions, and the table formatting,
# which gives its tables the shared width.
echo "=== 5b appendix C, supporting tables ==="
$PY build_appendix_c.py | tail -2

echo "=== 6/8 front-matter lists ==="
$PY add_front_matter_lists.py | tail -2

echo "=== 7/8 table formatting ==="
$PY normalise_tables.py | tail -2

# A rebuild that aborts mid-way leaves the figures describing superseded models
# while the tables describe the current ones, and nothing downstream notices: on
# 5 October rerun_after_pixelwise_config.sh died at its configuration-check
# stage and never reached make_figures.py, so the document carried plots of the
# previous pixel-wise models for a day. Checked here because this chain runs
# after every rebuild.
echo "=== 7b figure freshness ==="
$PY - <<'PYEOF2'
import os, re, sys, time
EV = "data/processed/evaluation"
ref = os.path.getmtime(os.path.join(EV, "table_3_3.csv"))
gens = open("build_chapter4.py").read() + open("build_chapter5.py").read()
stale = []
for name in sorted(set(re.findall(r'FIG\("([^"]+)"', gens))):
    p = os.path.join("figures", name)
    if not os.path.exists(p):
        stale.append((name, "MISSING"))
    elif os.path.getmtime(p) < ref:
        stale.append((name, time.strftime("%b %d %H:%M", time.localtime(os.path.getmtime(p)))))
if stale:
    print("  FIGURES PREDATE THE CURRENT MODELS:")
    for n, w in stale:
        print("    %-30s %s" % (n, w))
    print("  run make_figures.py and make_suitability_maps.py, then this chain again")
    sys.exit(1)
print("  all embedded figures are newer than table_3_3.csv")
PYEOF2

echo "=== 8/8 verify ==="
$PY - <<'PYEOF'
import os, re, docx
from docx.oxml.ns import qn
D = os.path.expanduser("~/Library/CloudStorage/OneDrive-Personal(2)/UNI ZIM/"
                       "PROJECT CHAPTERS/CR_Madukwe_Dissertation.docx")
d = docx.Document(D); x = d.element.xml
txt = " ".join(p.text for p in d.paragraphs)
# Narrowly the false claim about the scenario signal, not every use of the word:
# "the conversion back to irradiance inverts it exactly" is correct.
bad = {"false 'inverts' claim": len(re.findall(
           r"inverts (?:the scenario|outright)", txt)),
       "W m-2": len(re.findall(r"W m-2", txt)),
       "km2": len(re.findall(r"km2", txt)),
       "bare 2386": len(re.findall(r"\b2386\b", txt)),
       "[n] markers": len(re.findall(r"\[\d{1,2}\]", txt)),
       "El Nino": len(re.findall(r"El Nino", txt)),
       "empty headings": sum(1 for p in d.paragraphs
                             if p.style.name.startswith("Heading") and not p.text.strip())}
sig = {(t.style.name, t._tbl.tblPr.find(qn("w:tblW")).get(qn("w:w")))
       for i, t in enumerate(d.tables) if i}
ok = (not any(bad.values()) and len(sig) == 1 and len(d.sections) == 2
      and x.count('w:fldCharType="begin"') == x.count('w:fldCharType="end"'))
print("  citations %d | fields %d/%d | sections %d | tables %d (%d format) | images %d | words %d"
      % (x.count("ZOTERO_ITEM"), x.count('w:fldCharType="begin"'),
         x.count('w:fldCharType="end"'), len(d.sections), len(d.tables), len(sig),
         x.count("<a:blip"), sum(len(p.text.split()) for p in d.paragraphs)))
print("  defects:", {k: v for k, v in bad.items() if v} or "none")
print("  " + ("ALL CHECKS PASS" if ok else "CHECKS FAILED"))
raise SystemExit(0 if ok else 1)
PYEOF
