"""One line spacing, one alignment, black headings, consistent units and metadata.

The document reads as two theses stitched together because it is one: Chapters 1
to 3 are hand-written and justified, Chapters 4 and 5 are generated and
left-aligned, and the line spacing runs 1.5, 1.3, 1.2 and the style default. The
file also still claims python-docx as its author.

What this does NOT touch: table cell paragraphs, which were set deliberately by
normalise_tables.py and are reached through tables rather than through
Document.paragraphs; and the captions, which stay single-spaced because setting
them to 1.5 spaces a two-line caption as far as a paragraph.

Empty headings are DELETED rather than emptied, but only after checking each for
a section break. Removing a paragraph that carries one merges the front matter
into the body and loses the page numbering, which has happened in this project.
"""

import os
import re
import shutil
import sys

import docx
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor

CH = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-Personal(2)/UNI ZIM/PROJECT CHAPTERS")
DOC = os.path.join(CH, "CR_Madukwe_Dissertation.docx")
LOCK = os.path.join(CH, "~$_Madukwe_Dissertation.docx")

TITLE = ("Machine Learning-Based Downscaling of GCM Outputs for "
         "Solar Energy Suitability Mapping over Zimbabwe")
AUTHOR = "Chiagozie Raphael Madukwe"
BODY_SPACING = 1.5
CAPTION_SPACING = 1.0
# Matching the forty-one captions that already carried an explicit size.
CAPTION_SIZE = Pt(10)
# The letter class admits Appendix C's "Table C.1." captions, which this pass
# never matched and so never governed - they carried only whatever
# build_appendix_c.py set.
CAPTION = re.compile(r"^\s*(Table|Figure)\s+(?:\d+|[A-Z])\.\d+\.")

TEXT_FIXES = [
    ("El Nino", "El Niño"),
    ("La Nina", "La Niña"),
    ("km2", "km²"),
    ("W m-2", "W/m²"),
    ("2386", "2,386"),
    ("5751", "5,751"),
    ("0.25 °", "0.25°"),
    ("29.8 °", "29.8°"),
]


def is_field(run):
    x = run._r.xml
    return ("fldChar" in x) or ("instrText" in x)


def has_sectpr(p):
    pPr = p._p.find(qn("w:pPr"))
    return pPr is not None and pPr.find(qn("w:sectPr")) is not None


def main():
    if os.path.exists(LOCK):
        print("The dissertation is open in Word. Close it first.")
        return 2

    d = docx.Document(DOC)
    x = d.element.xml
    before = (x.count("ZOTERO_ITEM"), x.count('w:fldCharType="begin"'), len(d.sections))
    print("before:", before)

    # ---- metadata ----
    cp = d.core_properties
    cp.author = AUTHOR
    cp.last_modified_by = AUTHOR
    cp.title = TITLE
    cp.comments = ""
    print("metadata: author and title set, 'generated by python-docx' cleared")

    # ---- spacing, alignment, heading colour ----
    body = headings = captions = 0
    for p in d.paragraphs:
        name = p.style.name
        t = p.text.strip()
        if name.startswith("Heading"):
            for r in p.runs:
                r.font.color.rgb = RGBColor(0, 0, 0)
            # Thirty-six headings carried a direct 1.5 while ninety-two inherited
            # the style, which is the heading half of the mixed-spacing report.
            # The override is cleared rather than a value imposed, so every
            # heading takes the template's spacing and the template stays in
            # charge of heading format.
            p.paragraph_format.line_spacing = None
            headings += 1
            continue
        if not t or name == "Bibliography":
            continue
        pf = p.paragraph_format
        if CAPTION.match(t):
            # Captions were left alone by an earlier version, which is why they
            # ended up carrying three different spacings: single where a
            # generator set it, 1.5 where one was added by hand, and inherited
            # in Chapters 1 to 3. They are set to single here, uniformly, and
            # still kept out of the justification below.
            pf.line_spacing = CAPTION_SPACING
            # Size as well as spacing. Table 3.4's caption inherited the body
            # size while the other forty-one carried an explicit 10pt, so one
            # caption rendered larger than the rest.
            for r in p.runs:
                if r.font.size is None or r.font.size != CAPTION_SIZE:
                    r.font.size = CAPTION_SIZE
            captions += 1
            continue
        pf.line_spacing = BODY_SPACING
        if name in ("Normal",):
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        body += 1
    print("spacing set on %d body paragraphs and %d captions; %d headings set to black"
          % (body, captions, headings))

    # ---- empty headings ----
    killed = kept = 0
    for p in list(d.paragraphs):
        if p.style.name.startswith("Heading") and not p.text.strip():
            if has_sectpr(p):
                kept += 1
                continue
            p._p.getparent().remove(p._p)
            killed += 1
    print("empty headings: %d removed, %d kept because they carry a section break"
          % (killed, kept))

    # ---- text conventions ----
    counts = {}
    for p in d.paragraphs:
        for r in p.runs:
            if is_field(r) or not r.text:
                continue
            for old, new in TEXT_FIXES:
                if old in r.text:
                    counts[old] = counts.get(old, 0) + r.text.count(old)
                    r.text = r.text.replace(old, new)
    for t in d.tables:
        for row in t.rows:
            for c in row.cells:
                for p in c.paragraphs:
                    for r in p.runs:
                        if is_field(r) or not r.text:
                            continue
                        for old, new in TEXT_FIXES:
                            if old in r.text:
                                counts[old] = counts.get(old, 0) + r.text.count(old)
                                r.text = r.text.replace(old, new)
    print("text conventions:", counts or "nothing to change")

    shutil.copy(DOC, DOC.replace(".docx", "_BACKUP_pre_presentation.docx"))
    d.save(DOC)

    d2 = docx.Document(DOC)
    y = d2.element.xml
    after = (y.count("ZOTERO_ITEM"), y.count('w:fldCharType="begin"'), len(d2.sections))
    print("after: ", after)
    if after != before:
        shutil.copy(DOC.replace(".docx", "_BACKUP_pre_presentation.docx"), DOC)
        print("STRUCTURE CHANGED, restored from backup")
        return 1
    print("citation fields and sections intact")
    return 0


if __name__ == "__main__":
    sys.exit(main())
